# Generated by Django 2.1 on 2018-12-18 16:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20181218_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemap',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
