# Generated by Django 2.1 on 2018-12-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20181218_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
