# Generated by Django 2.1 on 2018-12-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
