# Generated by Django 2.1 on 2018-10-07 15:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('flat_no', models.CharField(blank=True, max_length=33, null=True)),
                ('building_no', models.CharField(blank=True, max_length=33, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=33, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=33, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=33, verbose_name='Country')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Address'),
        ),
    ]
