# Generated by Django 2.1 on 2018-10-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20181007_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='home_address',
        ),
    ]
