# Generated by Django 2.0.6 on 2018-08-19 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180817_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=28, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
