# Generated by Django 2.1 on 2018-08-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180825_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_prof',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
